### ISSUE TITLE
Hydrator $underscoreSeparatedKeys -> Umlauts not working

### ISSUE THREAD

**Issue by minimaex** [zendframework/zend-hydrator#51] opened 2017-03-17 10:07 UTC
Hello,

if I try to use the Hydrator with $underscoreSeparatedKeys I can not set Vars with Umlauts.
The $setterName in ClassMethods.php is only 'set'.

Pleas fix it :)

**Comment by froschdesign** [comment] 2017-03-17 10:10
@minimaex 
> if I try to use the Hydrator with $underscoreSeparatedKeys

You mean the hydrator `ClassMethods`?

> …I can not set Vars with Umlauts.
The $setterName in ClassMethods.php is only 'set'.

Sorry, but I don't understand the problem.
Please provide a short and reproducible example.

**Comment by minimaex** [comment] 2017-03-17 10:17
Yes with Hydrator ClassMethods.php.

$hydrator = new ClassMethods(true);
 $hydrator->hydrate($data, $entity);

The entity have "setKürzel()". And $data['Kürzel'] = 'test';
If i set the $underscoreSeparatedKeys = true
The function does not set this Variable. 

I tried to debug and find out, that the variable $setterName in public function ClassMethods->hydrate(array $data, $object) is only 'set'.

**Comment by froschdesign** [comment] 2017-03-17 10:44
> `$hydrator = new ClassMethods(true);`

You can remove `true` from the constructor. It is the default value.

> The entity has setKürzel()

Really ugly name, but [it works](http://php.net/manual/en/functions.user-defined.php).

> `$data['Kürzel'] = 'test'`

This will work only for the hydration, but not for extraction:

```php
var_dump($hydrator->extract($object)); // ['k_ürzel' => '…']
```

Use `$data['kürzel'] = 'test'` instead.

> I tried to debug and find out, that the variable `$setterName` in `ClassMethods->hydrate(array $data, $object)` is only 'set'.

I can not reproduce the problem. No problems on different PHP versions.
So, please remove the umlaut from your class and try again: `$data['kurzel'] = 'test';`

---

_Mixing different languages in variable, class and methods names is really confusing!_

**Comment by minimaex** [comment] 2017-03-17 10:53
OK thanks.
Cant understand, if i set 
$hydrator = new ClassMethods(false);

The Variable Kürzel is setted.

**Comment by froschdesign** [comment] 2017-03-17 10:59
@minimaex 
Right, because without the naming strategy `UnderscoreNamingStrategy` the names are not converted / filtered. The original name from the array is used.

**Comment by minimaex** [comment] 2017-03-17 11:07
But why is the Filter not Working with umlauts?

**Comment by froschdesign** [comment] 2017-03-17 11:20
> But why is the Filter not Working with umlauts?

This is not working on your system! Maybe [`mbstring`](http://php.net/manual/de/book.mbstring.php) is missing.
Please test the [underlying filters](https://docs.zendframework.com/zend-filter/word/#word-filters) on your system.

I will close this issue, because this is not a problem of `zend-hydrator`.

**Closed by froschdesign** 2017-03-17 11:20 UTC
